stages:
  train_tokenizer:
    cmd: python train_tokenizer.py --tokenizer-out .data/wmt20.bpetokenizer --dataset
      wmt20_mlqe_task1 --languages ru-en
    deps:
    - train_tokenizer.py
    outs:
    - .data/wmt20.bpetokenizer
